### ISSUE TITLE
Q: Is there a reason to use `lazysizes` over / in addition to `cloudinary-vue` lazy loading?

### ISSUE THREAD

**Issue by hartmut-co-uk** [mayashavin/portfolio-new#3]
Hi, just doing some reading of your source code and came across 
https://github.com/mayashavin/portfolio-new/blob/217b3c54173b7b3e96136b4091b4ae3a0cb8f7d9/components/MHeader.vue#L33-L44

So I'm just curious if there is any specific reason or known issues for using `lazysizes` (_line 43_ class `lazyload`) over / in addition to `cloudinary-vue` lazy loading (_line 36_ `loading="lazy"`)?

**Comment by mayashavin** [comment]
@hartmut-co-uk The truth is no, I was playing with `lazysizes` and forgot to remove it. It actually does nothing here since `lazyload` class only works on `img` afaik. I will remove it. Thanks :)
