### ISSUE TITLE
Firefox - Scrolling not working

### ISSUE THREAD

**Issue by mayashavin** [mayashavin/portfolio-new#4]

**Comment by Mini-ghost** [comment]
Hi! This personal website is very cool. I have read all the articles and learn a lot.

And I found a small problem. 

The scrollbar of some block is not smooth on iOS, when I scrolling.

I use iPhone 6 (iOS 12)

Thank you.

**Comment by mayashavin** [comment]
Hi @Mini-ghost thanks a lot :) I will check out the bug about scrolling as you mentioned. Is it slow or other specific problem?
